fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "buildenv": "git://github.com/camptocamp/puppetlabs-buildenv.git"
  symlinks:
    "ruby": "#{source_dir}"
