---
.travis.yml:
  forge_password: "HnBMIscjZVSI6BFaNrIsGeBXeLR1BxD6ag+P/RAmGHEmitAikI2FtkEUIMaqBsEcyVsnkTGknrhjyvVHOVB9I4brQ6qaz1xSFOELqi+Vb7hLnc4o3UOsNU+CKJD7KaQB8QZ3hjIXlxqTDO7mhi746kmHvsmtRfGEiQ8hK5CGk94="
